# Created by: Joe Marcus Clarke <marcus@FreeBSD.org>
# $FreeBSD: head/devel/mate-common/Makefile 367830 2014-09-10 13:11:28Z bapt $

PORTNAME=	mate-common
PORTVERSION=	1.8.0
CATEGORIES=	devel mate
MASTER_SITES=	MATE
DIST_SUBDIR=	mate

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	Common automake macros for MATE

PORTSCOUT=	limitw:1,even

USES=		gmake pkgconfig:both tar:xz
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
